"#version 130\n"
"\n"
"in vec4 feiVertex;\n"
"in vec2 feiTexCoord;\n"
"out vec4 v_color;\n"
"out vec2 v_texcoord;\n"
"out vec3 v_worldcoord;\n"
"\n"
"void main()\n"
"{\n"
"	v_color = gl_Color;\n"
"	v_texcoord = feiTexCoord;\n"
"	v_worldcoord = vec3(gl_ModelViewMatrix * feiVertex);\n"
"	gl_Position = gl_ModelViewProjectionMatrix * feiVertex;\n"
"}\n"
